#! /bin/sh
#
# (c) Copyright 2014 Gumstix, Inc.
# Licensed under terms of GPLv2
#
# Based on mk2PartSDCard.sh from Texas Instrument
# http://processors.wiki.ti.com/index.php/How_to_Make_3_Partition_SD_Card
#
# This script will create a boot partition 74 MB in size (9 * 255 * 63 * 512) and a rootfs that fills up the rest of the space in the SD card.
# example usage: $ sudo mk2partsd /dev/sdb

DRIVE=$1

dd if=/dev/zero of=$DRIVE bs=1024 count=1024

SIZE=`fdisk -l $DRIVE | grep Disk | awk '{print $5}'`

echo DISK SIZE - $SIZE bytes

CYLINDERS=`echo $SIZE/255/63/512 | bc`

sfdisk -D -H 255 -S 63 -C $CYLINDERS $DRIVE << EOF
,9,0x0C,*
10,,,,
EOF

mkfs.vfat -F 32 -n "boot" ${DRIVE}1
umount ${DRIVE}1
mkfs.ext3 -L "rootfs" ${DRIVE}2
